### ISSUE TITLE
Error compiling in ParameterData.cs

### ISSUE THREAD

**Issue by iinjdpa** [shtirlitsDva/Revit-PCF-Exporter#30]
In line 38:

public string ExportingTo { get; } = null; //Currently used with CII export to distinguish CII parameters from other PIPL parameters.

 it gives the error:
The token '=' is invalid in a class, struct or interface member declaration(CS1519)

**Comment by shtirlitsDva** [comment]
Remove "= null". See if it goes.
10 июля 2016 г. 4:50 PM пользователь "iinjdpa" <notifications@github.com>
написал:

**Comment by iinjdpa** [comment]
Thanks for your quick response. I am not c# programmer. I know only Python programming but I have experience in Revit.
It does not work.
Givesme the same error in lines 32 to 38.
'PCF_Functions.ParameterDefinition.Name.get' must declare a body because it is not marked abstract or extern. The implemented properties should automatically define the get and set accessor. (CS0840)

**Comment by shtirlitsDva** [comment]
Hi
Well, I am not a programmer, so I don't know exactly what is wrong.

It could be mismatching c# versions, different compilers.

I compile in Visual Studio 2015 Community Edition and receive no errors.
10 июля 2016 г. 5:14 PM пользователь "iinjdpa" <notifications@github.com>
написал:

**Comment by iinjdpa** [comment]
ok, perhaps it is the reason. I am using sharpdevelop. I will try Visual Studio too.

Thank you!!

**Comment by iinjdpa** [comment]
ok, perhaps it is the reason. I am using sharpdevelop. I will try Visual Studio too.

Thank you!!

**Comment by iinjdpa** [comment]
Compiled successfully with Visual Studio 2015 !!. Now I will install in Revit and let you know.
