### ISSUE TITLE
Where is the plugin?

### ISSUE THREAD

**Issue by xnaldo** [shtirlitsDva/Revit-PCF-Exporter#44]
hyperlinks are not working. I could not download the plugin.

**Comment by xnaldo** [comment]
It works for valves too? Will export the valves and flanges to PCF?

**Comment by shtirlitsDva** [comment]
Hi. It works for flanges and valves. There are not any links to download --
you have to compile it yourself.

**Comment by xnaldo** [comment]
Hi, I tried to compile but I am a nubbie on this... Could you send a more precise step by step? Maybe a video tutorial...

**Comment by shtirlitsDva** [comment]
Hi, the compile process is --> clone the project --> open it in Visual Studio Community 2019 --> in the solution explorer go to references and add missing references for .dll files (they are usually in the Revit install directory).
Write to me app@mgtek.dk we can also try to do a live session on Teams

**Comment by Unalkosedag** [comment]
Hello
I wanted to install this Revit PlugIn but I am missing the .dll file. Can you help me please?
Thank you for your support.

**Comment by shtirlitsDva** [comment]
Hi. You have to compile it yourself.

вс, 19 сент. 2021 г., 10:48 Unalkosedag ***@***.***>:
