### ISSUE TITLE
PCF -> Excel

### ISSUE THREAD

**Issue by MSp-RVT** [shtirlitsDva/Revit-PCF-Exporter#45]
Hello, 

i have a little Problem with creation an Excel schedule. I always get this error message in Revit
![1606941417537](https://user-images.githubusercontent.com/75394084/100929076-58647380-34e7-11eb-822a-c8c1d30525bf.png)

Please help me :)

**Comment by shtirlitsDva** [comment]
Seems like there's something wrong with the Microsoft.Office.Interop.Excel on your computer. I haven't used this part of the code for quite some time, so I am not aware of any issues currently. Try searching online for a solution.

**Comment by MSp-RVT** [comment]
I have newly installed Excel. Now the error message is gone. However, I get a different message. Do you know what this means






Informationen über das Aufrufen von JIT-Debuggen
anstelle dieses Dialogfelds finden Sie am Ende dieser Meldung.
 
************** Ausnahmetext **************
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei PCF_Parameters.ExportParameters.ExecuteMyCommand(UIApplication uiApp) in C:\Users\micha\Downloads\Revit-PCF-Exporter-master\Revit-PCF-Exporter-master\revit-pcf-exporter\PCF_Parameters.cs:Zeile 151.
   bei PCF_Exporter.PCF_Exporter_form.button9_Click(Object sender, EventArgs e) in C:\Users\micha\Downloads\Revit-PCF-Exporter-master\Revit-PCF-Exporter-master\revit-pcf-exporter\PCF_Exporter_form.cs:Zeile 385.
   bei System.Windows.Forms.Control.OnClick(EventArgs e)
   bei System.Windows.Forms.Button.OnClick(EventArgs e)
   bei System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ButtonBase.WndProc(Message& m)
   bei System.Windows.Forms.Button.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
