### ISSUE TITLE
Issue with Visual Studio

### ISSUE THREAD

**Issue by LIngenao** [shtirlitsDva/Revit-PCF-Exporter#46]
Hello, 

I am a regular French Revit user but I have never used Visual Studio, I think I managed to compile the whole : 

I inserted the API and APIUI files.
And then for compile i click on Start debugging
But then I don't understand how to get a DLL out of it and I don't understand either if I have to export the solution or the projects?

Thanks in advance for your help!

**Comment by shtirlitsDva** [comment]
Hi. There's a lot of guides on the internet, where you can learn this.
Sorry, but I don't have time to help with basic stuff.

пн, 4 апр. 2022 г., 15:55 LIngenao ***@***.***>:
